### ISSUE TITLE
Schedule meetings given time-slot availabilities and who is needed at meetings

### ISSUE THREAD

**Issue by jameshowison** [timnon/pyschedule#10]
Can this be used to schedule meetings into time-slots where not all resources are available for a particular timeslot?

So far I've thought to model the meetings as tasks and the people as resources. And then say which resources (people) are needed for each meeting.

So far so good :) But I'm not sure how to model which periods some of the resources are not available? Is it perhaps the CAPSLICE parameter? Or might I approach it by modeling the time periods as resources as well?

Thanks,
James

**Comment by timnon** [comment]
Hi,
not sure if I understand the question correctly, but you can block resources by simply setting the capacity to 0 during some time periods, like 

```
S += R['length'][4:10] <= 0
```

Basically means that the length of all tasks on resource R from period 4 to 10 needs to be 0, ergo no task can be scheduled.
