### ISSUE TITLE
forcing 2 tasks to be at the same time

### ISSUE THREAD

**Issue by fderyckel** [timnon/pyschedule#12]
Hi @timnon , 
First, thank you so much for making pyschedule and letting us enjoy it.

I was wondering if it is possible to create the following scenario. 
T1 += R1
T2 +=R2

Now I want T1 and T2 to be scheduled at the same time.  How do we go about that?

I know I can do 
s += T1 < T2
or even
s += T1 <= T2

But it seems I cannot do 
s += T1 == T2

Would there be a work around for that?

Thanks in advance.

Best,

**Comment by timnon** [comment]
Hi,
T1 <= T2 + T1.length
should do the job.

Unfortunately, it is not good to overload the == operator, which would make sense here

**Comment by fderyckel** [comment]
Hi @timnon ,
Thanks for replying so promptly.  
Unfortunately it didn't do the job for me.  I do like the idea tough.  
The workaround I used: Since two task have to happen at the same time for 2 different resources, I've created one task instead and assign it to the 2 resources.

**Comment by timnon** [comment]
good solution, if you want these tasks to have different lengths, then you can also pad another dummy task to the longer of the two tasks, just a comment
