### ISSUE TITLE
Adding optional resources in loop

### ISSUE THREAD

**Issue by jpk0727** [timnon/pyschedule#14]
Hi,

I am attempting to assign a variable amount of optional resources to a task in a loop like so:

`T += R[0] | R[1] | R[2] | ... | R[n]`

However, adding R as an array creates multiple tasks. For example, this does not achieve the desired result:

`T += R`

A solution I came up with that works is by creating a string in a loop the is the command I would like to executue and the calling the exec() function like so...

```python
exec_str = "T[i] +="
for i in range(len(R)):
    exec_str+=" R["+str(i)+"] "
    if (i != len(R) - 1):
        exec_str+= "|"
exec(exec_str)
```

This solution, however, seems pretty ugly to me. Anybody see any better alternatives?

Thanks,
Jess

**Comment by timnon** [comment]
Hi,
you can use the "alt"-method, e.g.

from pyschedule import alt
T += alt([ R[i] for i in range(n) ])
