### ISSUE TITLE
Is this kind of problem solvable? 

### ISSUE THREAD

**Issue by RickCogley** [timnon/pyschedule#19]
Hello - forgive the newbie question but, I wonder, is it possible to use your module for this kind of problem? :

I have: 

* list of patients at hospitals
* list of roaming doctors
* list of possible dates next month, to work
* list of constraints, such as "patient 10 is not available mondays", "doctor 3 is not available 4 May 2017", "a doctor can see only 15 patients per day", "a doctor can work only 2 days per week"

I would like to solve this and get a list of suggested dates to schedule, that don't have any conflicts.

Just trying to wrap my head around how this would be done using your module @timnon. Appreciate any guidance you can provide. 

Sincerely,
Rick

**Comment by timnon** [comment]
Sorry for the late reply. That is a perfect application of pyschedule, check the example: https://github.com/timnon/pyschedule-notebooks/blob/master/employee-scheduling.ipynb 

The only limitation is the size of the problem, if you have hundreds of doctors, solving the problem might become hardm
