### ISSUE TITLE
schedule for telescope time and tricky constraints

### ISSUE THREAD

**Issue by starrywheat** [timnon/pyschedule#22]
I am using the library to schedule observing time at the telescope site. The setting/problem of the observation schedule goes like this:

Resource: 
X hours of telescope time
telescope = S.Resource('telescope')

Tasks: 
celestrial objects (e.g. star A, star B) that need to be observed of Y hours each. 
starA = S.Task('StarA', Y)
starB = S.Task('StarB', Y)

Constraints:
Each celestial target are only available at a certain time of the day. E.g. starA 17:00-20:00, starB 00:00-04:00. And the telescope can point to a star at a time. So I convert this into having the tasks, i.e. starA, starB, to have the condition:
S += starA + 7 << starB
S += starB + 11 < starB

In addition, there are 'recharge' tasks to do for the telescope. The telescope need to be 'recharged' for Z hours and then can run for the next R hours. Let's say we know we want to observe for 2 days and need 2 recharge, i.e.
recharge1 = S.Task('Recharge1', Z)
recharge2 = S.Task('Recharge2', Z)

Now my question is how to setup constraints so it can assign the two recharge tasks properly such that they are done within the R hours from the previous recharge tasks. The tricky part is the current <=, <, or << constraints don't do this requirement properly, as these operators seem to give hard bound between tasks, instead of a range.

Hope you can give some insight.

**Comment by timnon** [comment]
Sorry for the late reply. Could this work:

recharge1 < recharge2
recharge2 < recharge1 + R + Z

This would imply that there are two recharge tasks scheduled in the right order and the second one is started at most R hours after the first
