### ISSUE TITLE
fix a limit of tasks in a resource

### ISSUE THREAD

**Issue by djking7** [timnon/pyschedule#23]
Is their any way to limit number of tasks per resource?

**Comment by timnon** [comment]
Yes, using capacity constraints

**Comment by timnon** [comment]
Check the CAP feature here: https://github.com/timnon/pyschedule/blob/master/docs/pyschedule-overview.md

**Comment by timnon** [comment]
There are quite some capacity constraints in this example: https://github.com/timnon/pyschedule-notebooks/blob/master/employee-scheduling.ipynb

**Comment by timnon** [comment]
There are quite some capacity constraints in this example: https://github.com/timnon/pyschedule-notebooks/blob/master/employee-scheduling.ipynb

**Comment by djking7** [comment]
I'm not talking about the sum of the lengths of the tasks assigned to R1. I have no idea about the length, I want to limit the number of tasks without knowing the length.
for example R1 can do 5 tasks (T1, T2, T3, T4, T5)

**Comment by HBouch** [comment]
Any solution found or not yet ?

**Comment by timnon** [comment]
You can do this by giving tasks another uniform "count" parameter instead of using the length and limit this with a capacity constraint, like:

```
T1.count = 1
T2.count = 1
...
S += R['count'] <= 5
```
