### ISSUE TITLE
Single task to multiple Jobs

### ISSUE THREAD

**Issue by James3539** [timnon/pyschedule#24]
Hi am using Pyschedule to try and optimize my complex ETL process.  I extract multiple tables from an ERP system and create about 50 different models. Each model can only start once all the required tables for that model is extracted.  Most tables goes to multiple models and some extracts run for quite a long time.  

Any help would be highly appreciated.

**Comment by dokechin** [comment]
Thank you very much, I solved this problem , sorry my coding bug.

**Comment by timnon** [comment]
Is this issue still open?
