### ISSUE TITLE
How to handle big task across holidays?

### ISSUE THREAD

**Issue by crayster** [timnon/pyschedule#3]
Hello there,
I'm not sure whether CAPSLICE is supported by mip.solve, it seems YES according to the test result.

Assume a simple scenario:
```
S = Scenario('test1', horizon=10)

# only one task, consuming 7 days
T1 = S.Task('T1', 7)

# only one resource, not work in weekend
R1 = S.Resource('R1')
S += S['R1']['length'][5:7] <= 0

S['T1'] += S['R1']
solvers.mip.solve(S)
```

Expected result is:
`[(T1, R1, 0, 9)]`

but returned:
`[(T1, R1, 0, 7)]`

Any idea? Thank you very much!

**Comment by timnon** [comment]
thanks for the valuable feedback. The main problem is that tasks are non-preemptive by default, that means that they cannot be split into two parts. If a task with length 7 starts in some period x, then it needs to run for 7 consecutive periods starting with x.

For the scenario above, you could split T1 into 7 tasks of length 1:

```python
from pyschedule import Scenario, solvers
S = Scenario('test1', horizon=10)

# 7 tasks, each consuming one day
n_days = 7
tasks = [ S.Task('T_%i'%i) for i in range(n_days) ]
# order tasks
S += [ tasks[i] < tasks[i+1] for i in range(n_days-1) ]

# only one resource, not work in weekend
R1 = S.Resource('R1')
S += S['R1']['length'][5:7] <= 0

# all tasks need the same resource
for T in tasks:
	T += S['R1']

# finish tasks as soon as possible
S.use_flowtime_objective()

solvers.mip.solve(S)
print(S.solution())
```

returns

```python
[(T_0, R1, 0, 1), (T_1, R1, 1, 2), (T_2, R1, 2, 3), (T_3, R1, 3, 4), 
(T_4, R1, 4, 5), (T_5, R1, 7, 8), (T_6, R1, 8, 9)]
```
I added the usage of the flowtime objective to ensure that tasks are pushed to the beginning of the planning horizon as much as possible.

**Comment by timnon** [comment]
I spotted a pretty technical problem in this context: what if there is a capacity restriction on a slice of a resource and a longer task only partially overlaps with this slice? Should the whole weight of the task be used in the capacity restriction? Should it be scaled somewhat?

There is no clear answer, but the following default probably makes the most sense:

**For each period in the capacity restriction slice that the task overlaps with, assign the whole weight of the task divided by the length of the task**

For instance, if a task has length 7 and overlaps in 3 periods, then the weight of the task in the capacity restriction will be 3*length/length=3*7/7 = 3. Hence, the fraction of the overlap.

**Comment by timnon** [comment]
The adaption in the last comment has been committed

**Comment by crayster** [comment]
Hi, Timno! Thanks for your reply.
Yes, you are right. For my case, splitting task is the answer.

And by the way, with your last commit, in my case solve(S) will return 0 now.
I think this answer is better than the old one, because there isn't "7 consecutive periods" indeed.

**Comment by timnon** [comment]
One more comment, in case you have "similar" tasks such that they could replace each other, it makes sense to group them, this will greatly speed up the computation (absolutely necessary for large problems). For instance, the 7 tasks above are completely the same except for the name, so lets add them to the same group, called mygroup:

```python
from pyschedule import Scenario, solvers
S = Scenario('test1', horizon=10)

# 7 tasks, each consuming one day
n_days = 7
tasks = [ S.Task('T_%i'%i,group='mygroup') for i in range(n_days) ]

# only one resource, not work in weekend
R1 = S.Resource('R1')
S += S['R1']['length'][5:7] <= 0

# all holidays need the same resource
for T in tasks:
	T += S['R1']

# finish tasks as soon as possible
S.use_flowtime_objective()
solvers.mip.solve(S)
print(S.solution())
# returns [(T_0, R1, 0, 1), (T_1, R1, 1, 2), (T_2, R1, 2, 3), (T_3, R1, 3, 4),
#          (T_4, R1, 4, 5), (T_5, R1, 7, 8), (T_6, R1, 8, 9)]

```

The scheduling order of these tasks is then simply the order in which they have been added to the problem, so no precedence relations (the <) required. In this extremely simple problem, the computation is roughly twice as fast when tasked are grouped. This does not really matter because the computation time is milliseconds anyway, but it makes a huge difference for large problems.
