### ISSUE TITLE
Representing maximum duration

### ISSUE THREAD

**Issue by tpaviot** [timnon/pyschedule#40]
I'd like to represent the fact that a resource is available only 4 hours a day. That is to say that the total amount of tasks ran by this resource has to be between 8.00 AM and 12.00, or between 8.30 and 12.30, or 13.30 17.30 etc. What kind of constraint should I add ? If 1 is "one hour", then in pseudo code, the constraint I have in mind would be
```
S += (end_of_last_task - start_of_first_task) < =4
```
Is there something similar that I could use in the list of resource constraints ?

**Comment by timnon** [comment]
There is unfortunately no contraint to enforce this directly, but you can add a high penalty if this constraint is not satisfied .e.g:
```
T_start, T_end = S.Task('start'), S.Task('end')
S += T_end > T_start + 4 #T_end should start earliest four time steps after T_start
S += T_end - T_start #this adds the difference to the objective, so it will try to schedule T_end T_start as late as possible and T_end as early as possible. If there are other objectives to compete, add a large constant to enforce this like 1000*(T_end - T_start)
```

**Comment by timnon** [comment]
Try this one:
```
# working day with eight hours
from pyschedule import Scenario, solvers, plotters, Task
S = Scenario('shift_bounds',horizon=8)

# define two employees
empl0 = S.Resource('empl0')
empl1 = S.Resource('empl1')

# employee 0 starts at two and ends
# at most four hours later
empl0_beg = S.Task('empl0_beg',completion_time_cost=2)
empl0_beg += empl0
empl0_fin = S.Task('empl0_fin',completion_time_cost=2)
empl0_fin += empl0
S += 2 <= empl0_beg, empl0_fin < empl0_beg + 6

# employee 1 begins at any time and finishes
# at most four hours later
empl1_beg = S.Task('empl1_beg',completion_time_cost=2)
empl1_beg += empl1
empl1_fin = S.Task('empl1_fin',completion_time_cost=2)
empl1_fin += empl1
S += empl1_fin < empl1_beg + 6

# interchangeable tasks that need to be finished as 
# by the two employees as early as possible
T = S.Tasks(group='T',n_tasks=6)
T += empl0 | empl1

# bound tasks of employees by shift begin and finish
S += empl0_beg << T, T << empl0_fin
S += empl1_beg << T, T << empl1_fin

if solvers.mip.solve(S,msg=1,kind='CBC'):
	plotters.matplotlib.plot(S)
else:
	print('no solution found')
```

The `<<` operator is a conditional `<` and only holds if a task is on the same resource. Hence, we can use this to define the begin and finish of a shift

**Comment by tpaviot** [comment]
I updated to the latest 0.2.21, the result is quite convincing. I did not understand the conditional precedence ```<<``` syntax, it's much more clear now. Thank you very much for your answer.

![figure_1](https://user-images.githubusercontent.com/660130/39419114-8e9b0a64-4c5e-11e8-8ede-b0693c441ae1.png)

**Comment by timnon** [comment]
the conditional precedence constraint has actually changed a little, but it makes more sense this way
