### ISSUE TITLE
Not Fulltime

### ISSUE THREAD

**Issue by pasha76** [timnon/pyschedule#6]
I am trying to schedule multiple projects and resources. I had a problem with assigning some percent of the employee to a given task.

I mean lenght of a task and effort of a task can be different. How can I assign some of the employee's effort to a task?

Thanks

**Comment by miketwo** [comment]
Take a look at https://github.com/timnon/pyschedule/blob/master/docs/pyschedule-overview.md

From your description, I think you might want to use the "cumulative resources" constraint. You can divide your employee up into 5 or 10 "parts", representing a percentage of their time, and then label tasks as taking a certain number of employee parts.

**Comment by pasha76** [comment]
I had tried that but I got error as below

   cook += Alice*2
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyschedule/pyschedule.py", line 852, in __mul__
    return _ResourceAffine(self).__iadd__(other)
AttributeError: '_ResourceAffine' object has no attribute '__iadd__'

What might be the reason?

**Comment by tximiss** [comment]
+1

**Comment by timnon** [comment]
Sorry for the late reply, there was a simple bug which should be fixed in the new version 0.2.15, please update
