### ISSUE TITLE
Slowdown between 0.2.25 and 0.2.30

### ISSUE THREAD

**Issue by kindlyfire** [timnon/pyschedule#68]
I noticed a big slowdown between version 0.2.25 and version 0.2.30. I use my school's schedule as my benchmark.

Time on 0.2.25: `<0.5s`
Time on 0.2.30: `~7s`

The data and the script I use is here: [repo](https://github.com/kindlyfire/exam-scheduler/tree/master/solver).
Log for `0.2.25`/`0.2.30`: [gist](https://gist.github.com/kindlyfire/e116e3f431dd4414f517b12e0df2ca80)

**Comment by timnon** [comment]
Thanks for the info, i will investigate this, maybe its also related to the used CBC solver

**Comment by timnon** [comment]
For me, version 0.2.30 takes 4.5 secs and has this output when the solving process starts:

```
At line 2 NAME          MODEL
At line 3 ROWS
At line 4829 COLUMNS
At line 22941 RHS
At line 27766 BOUNDS
At line 28376 ENDATA
Problem MODEL has 4824 rows, 609 columns and 16284 elements
Coin0008I MODEL read with 0 errors
ratioGap was changed from 0 to 0
Continuous objective value is 637.5 - 0.01 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 35 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 21 strengthened rows, 0 substitutions
Cgl0004I processed model has 433 rows, 609 columns (609 integer (609 of which binar
y)) and 2870 elements
```

Version 0.2.25 takes 0.2 secs, but has the same initial output, very strange:
```
At line 2 NAME          MODEL
At line 3 ROWS
At line 4829 COLUMNS
At line 22941 RHS
At line 27766 BOUNDS
At line 28376 ENDATA
Problem MODEL has 4824 rows, 609 columns and 16284 elements
Coin0008I MODEL read with 0 errors
ratioGap was changed from 0 to 0
Continuous objective value is 0 - 0.01 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 35 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 21 strengthened rows, 0 substitutions
Cgl0004I processed model has 433 rows, 609 columns (609 integer (609 of which binar
y)) and 2870 elements
```

**Comment by timnon** [comment]
Found the problem, i changed the defaults for the `completion_time_cost` of tasks from `None` to `1`, because it is almost always required that tasks should be scheduled as early as possible. Didnt expect this to have an impact on the performance (and if, then more on the positive side). I will switch this back in the next version, you can work-around by manually setting the `completion_time_cost` in you code with:

```
courses[course] = task = scen.Task(course, info["length"], completion_time_cost=None)
```

Thanks again for pointing this out

**Comment by kindlyfire** [comment]
Thank you ! 👍

**Comment by kindlyfire** [comment]
Just for information, I've made open-source my graduation project using pyschedule. It's an exam scheduler: [planex](https://github.com/kindlyfire/planex)

**Comment by timnon** [comment]
Pretty awesome! I will have a look
