### ISSUE TITLE
Constrains for a group of tasks

### ISSUE THREAD

**Issue by jm-imca** [timnon/pyschedule#70]
Hi there, first thing first, thanks a lot for your effort you put into this project!
First time I am playing with this type of thing, but I get stuck with one condition that I can not bring to work:
First I created three long task and was wondering how to make it that the tasks are automatically assigned to multiple people. I think this is not possible in a way that they share the work. So I splitted the tasks into group of tasks each one day long. This works well, the day task are shared between two persons.

 But one group of development tasks (webback_d) should be scheduled AFTER the task "sysarch", but I can not bring it to work. Here is my code: 

```
# Load pyschedule and create a scenario with ten steps planning horizon
from pyschedule import Scenario, solvers, plotters
S = Scenario('hello_pyschedule',horizon=50)


# Create some resources
Nick, Jim, Peter, Bob = S.Resource('Nick',size=1), S.Resource('Jim',size=1), S.Resource('Peter',size=1), S.Resource('Bob',size=1)


sysarch = S.Task('ARC',3,plot_color='#66FFff')
webfront_d = S.Tasks('GUI',num=10,length=1,is_group=True,plot_color='#6699ff')
webback_d = S.Tasks('SRV',num=15,length=1,is_group=True,plot_color='#FF99ff')
   
# Assign tasks to resources
webfront_d += Jim
webback_d += Peter | Nick
sysarch += Nick | Bob

#Here I try to define that all tasks in the group webback_d should only happen after the task sysarch is completed:
for task in webback_d:
    S += sysarch < task

solvers.mip.solve(S,msg=1)

print(S.solution())
plotters.matplotlib.plot(S,show_task_labels=True,fig_size=(10,5))
```

**Comment by jm-imca** [comment]
Sorry for the bad formatting !

**Comment by jm-imca** [comment]
Thanks Tim, that was a quick one! I 'll try it out! 
As you have not complained - so is my approach to cut a task into day pieces for sharing it with multiple workers so far the recommended approach?

**Comment by timnon** [comment]
Yes, your approach is exactly right, because all the parts of the long tasks are interchangeable, so it's good to organize them in a group for performance reasons.
