### ISSUE TITLE
Possible bug: Unable to block a resource during a period of time

### ISSUE THREAD

**Issue by adamgotterer** [timnon/pyschedule#75]
I'm trying to setup my resources to have specific workers hours. They are not allowed to work outside of those hours. So in the case where they could start a task during working hours but would need additional hours to finish the task the task be rejected. I've tried setting a combination of periods and length but I can't seem to restrict the job into the working ranges. Any thoughts? Thanks!

```python
from pyschedule import Scenario, solvers

S = Scenario('hello_pyschedule', horizon=24)

Alice = S.Resource('Alice')
S += Alice['length'][0:8] <= 0
S += Alice['length'][13:24] <= 0

Bob = S.Resource('Bob')
S += Bob['length'][0:12] <= 0
S += Bob['length'][14:24] <= 0

task1 = S.Task('Task1', length=5, completion_time_cost=1, periods=range(9,18))
S += task1 < 18
task1 += Alice | Bob

task2 = S.Task('Task2', length=1, completion_time_cost=1, )
S += task2 < 18
task2 += Alice | Bob

solvers.mip.solve(S, msg=0)
print(S.solution()) 
```

Output:
```
> [(Task2, Alice, 8, 9), (Task1, Alice, 9, 14)]
```

I wouldn't expect this solver to fail since theres no possible window of time to start and complete task1 within these constraints.

**Comment by adamgotterer** [comment]
This is starting to feel like a bug. If I remove the second task the solver has no solution. Once you add the second task in it seems to have a solution. Does that make sense to you?

```
from pyschedule import Scenario, solvers

S = Scenario('hello_pyschedule', horizon=24)

Alice = S.Resource('Alice')
S += Alice['length'][0:8] <= 0
S += Alice['length'][13:24] <= 0

Bob = S.Resource('Bob')
S += Bob['length'][0:12] <= 1
S += Bob['length'][14:24] <= 1

task1 = S.Task('Task1', length=5, completion_time_cost=1, periods=range(9,18))
S += task1 < 18
task1 += Alice | Bob

#task2 = S.Task('Task2', length=1, completion_time_cost=1, )
#S += task2 < 18
#task2 += Alice | Bob

solvers.mip.solve(S, msg=0)
print(S.solution()) 
```

```
> Cant be solved
```

Same setup with the addition

**Comment by timnon** [comment]
For the second message: there was indeed a subtle bug for the combination of period restrictions, capacities and tasks with length > 1. Thanks for testing carefully. Please update to the newest version 0.2.34.

However, this will turn both your scripts unsolvable for the reason as documented in the README: https://github.com/timnon/pyschedule/blob/master/README.md . Go to the section about capacities and non-unit tasks. Also happy to get feedback about this new documentation.

More specifically, your task1 has length 5, and so it will always "overlap" with the second capacity constraints if it has to start in period 9 the earliest, thus contributing to this constraint proportionally to its overlap. In general, tasks will contribute to capacity constraints proportionally to how much they overlap with the constraint. We could also make this absolute: As soon as the task overlaps just with one period, it will completely contribute. But i think the selected option makes somewhat more sense in most use cases.

Depends on what you want to model, there are probably ways to take this into account?

P.S. `completion_time_cost` has been renamed to `delay_cost`. The former still works, but was far too much work to type:)

**Comment by ollamh** [comment]
Hi @timnon , @adamgotterer !
I'm having the same problem:
```python
import pyschedule
s = pyschedule.Scenario('test_periods', horizon=200)
t1 = s.Task('Graphics_1', length=4)
t2 = s.Task('Graphics_2', length=4)
resource = s.Resource('Dep', periods=range(20,200))  #   <---| Are these two ways of place constraint mutually exclusive?
s += resource['length'][0:20] <= 0                   #   <---|      
s += resource['length'][24:100] <= 0                 #   <---|
s += t1 < t2
t1 += resource
t2 += resource
pyschedule.solvers.mip_bigm.solve(s, kind='SCIP', msg=1, ratio_gap=1.2)
print(s.solution())
pyschedule.plotters.matplotlib.plot(
    s, resource_height=100.0)
```
What I expect:
```python
[(Graphics_1, Dep, 20, 24), (Graphics_2, Dep, 100, 104)]
```
What I get:
```python
[(Graphics_1, Dep, 0, 4), (Graphics_2, Dep, 4, 8)]
```
Please, correct me if I'm mistaken expecting this behavior. I'm not sure if I can put these constraints into tasks definitions.

**Comment by adamgotterer** [comment]
@timnon my bug is resolved in the latest release. Thank you. I'll take a look at the updated docs and see if I understand it and if anything stands out.

I'm going to leave this ticket open so that @ollamh has his issues resolved in case its related

**Comment by adamgotterer** [comment]
@timnon overall the documentation in the capacities section makes sense. I struggled a bit with https://github.com/timnon/pyschedule/blob/master/README.md#bounding-differences and had a tough time following exactly what was happening and why.

**Comment by ollamh** [comment]
> @ollamh please use the normal mip-solver (either with SCIP or CBC):
> 
> ```
> pyschedule.solvers.mip.solve(s, kind='SCIP', msg=1, ratio_gap=1.2)
> ```
> The bigm-formulation is extremely limited and only kept for historic reasons, should be stated more clearly in the documentation.

@timnon Thank you very much, that did work (of course, stupid me)!
