### ISSUE TITLE
No module named 'pulp.solvers'

### ISSUE THREAD

**Issue by CaVaBienAller** [timnon/pyschedule#98]
I get the following error when executing "from pyschedule import Scenario, solvers, plotters":

ModuleNotFoundError: No module named 'pulp.solvers'

Should I install other packages before executing the HelloWorld example?
NOTE: I'm using PyCharm

Thanks in advance!

**Comment by kunesj** [comment]
I had identical problem. 
It seems to happen, if you have PuLP package version 2.1 or greater. 
Manually installing version 2.0 fixed it for me. (`pip3 install PuLP==2.0`)

**Comment by CaVaBienAller** [comment]
Excellent, the import works! Thanks for your help!
